### ISSUE TITLE
Add support for RPM based package installation

### ISSUE THREAD

**Issue by bschonec** [nvergottini/puppet-ir_agent#5]
I have taken the time to create an RPM package of the ir_agent.  Would adding RPM support be something you'd be willing to add to this project if I submit the changes?

**Comment by nvergottini** [comment]
How would you pass the --token and --https-proxy (if needed) parameters to the installer in the RPM? Would you have to build that into the RPM? Would you provide the spec file to build the RPM?

**Comment by bschonec** [comment]
There are a couple of options.  My RPM spec file accepts a command-line argument:

rpmbuild -ba --define '_token=us:1241212-412433-123412-23423'

and inside the spec file it contains:

./token_handler -token %{_token} -filepath $(pwd)

This will reach out to Rapid7 and create the certificates in the $BUILD directory and then the spec file takes care of copying those certificates to their proper locations in $BUILDROOT.

I'm sure this is not best practices as this hard-codes the certs into the RPM.

If you don't want to include the certificates in the RPM then you can simply copy those files (pre-generated via another process) after installing the RPM.  In my testing, the agent performed identically as it would when using the agent_installer script.

I created the RPM tarball (source) by duplicating the process that the script performs (by running bash -x ./agent_installer.sh).  I am a complete amateur with RPM building and have been out of the Puppet scene for about four years so I'm a bit rusty with that, too.  I'm hoping that when I push my rpm build project to Github, people smarter than me will contribute and make the project better.  

I've tested my idea on three different RHEL servers and all of them *seem* to be working fine.  They even updated themselves to the latest agent (which I think is a no-no) so that makes me think that my code is working.

https://github.com/bschonec/rapid7-rpmbuild

**Comment by nvergottini** [comment]
My issue with RPM is that the Insight agent is a self-updating agent, so you end up with a situation where the agent version installed doesn't match the RPM installed. I have that issue with CrowdStrike Falcon Sensor because they do distribute it as an RPM, but when Falcon Sensor self-updates, it doesn't do it using an RPM, so the agent version typically never matches the RPM. As you said, that seems like a no-no.

My concern with this is that it seems like it might not be supported by Rapid7.

**Comment by nvergottini** [comment]
I see you have the tarball for the agent in your repo. Are you sure that is okay?

**Comment by bschonec** [comment]
Indeed, that would be the behavior.  I'm kind of old-school when it comes to installing packages on Linux.  I think it's poor practice (and frankly, lazy) for the vendors *not* to provide RPM packages for linux.  Automatic updating behind the scenes make me twitchy, too.  Perhaps I'm blinded by my opinions on software installation regarding this.

**Comment by bschonec** [comment]
There's nothing proprietary in that tarball.  It's just a:

tail --bytes=-41581152 agent_installer.sh | tail --bytes=+21401826 | head -c +20179324 > rapid7-2.7.5-1.tar.gz

**Comment by bschonec** [comment]
I think I'm going to close out this issue.  It is a lot of work just to enforce my opinions about package installation.  Perhaps this is one of those times I should just go with the flow....
